<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class BpBlocks {
	private $bp_blocks_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'bp_blocks_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'bp_blocks_page_init' ) );
	}

	public function bp_blocks_add_plugin_page() {
		add_options_page(
			'bp-blocks', // page_title
			'bp-blocks', // menu_title
			'manage_options', // capability
			'bp-blocks', // menu_slug
			array( $this, 'bp_blocks_create_admin_page' ) // function
		);
	}

	public function bp_blocks_create_admin_page() {
		$this->bp_blocks_options = get_option( 'bp_blocks_option_name' ); 
		$trans_lang      = array(
			'woofc'         => array(
				'name'      => 'Fly Cart プラグイン',
				'lang_slug' => 'woofc',
				'plg_slug'  => 'woo-fly-cart',
				'lang_dir'  => 'languages',
			),
			'woocustomizer' => array(
				'name'      => 'WooCustomizer プラグイン',
				'lang_slug' => 'woocustomizer',
				'plg_slug'  => 'woocustomizer',
				'lang_dir'  => 'lang',
			),
		);

		if ( isset( $_POST['cmd'] ) && 'bp-blocks-settings' === $_POST['cmd'] ) {
			check_admin_referer( 'bp-blocks' );
			global $bpb_plugin_dir_path;

			$msg_success     = array();
			$msg_error       = array();
			$plugins_path    = trailingslashit( dirname( $bpb_plugin_dir_path ) );
			$wpcore_lang_dir = WP_CONTENT_DIR . '/languages/plugins/';
			$loco_lang_dir   = WP_CONTENT_DIR . '/languages/loco/plugins/';
			$bpb_lang_dir    = $bpb_plugin_dir_path . 'languages/';

			foreach ( $_POST[ 'bpb' ] as $key => $v ) {
				switch ( $key ) {
					case 'use_woocommerce':
						if ( (bool) $v ) {
							update_option( 'bp_block_use_woocommerce', true, false );
						} else {
							delete_option( 'bp_block_use_woocommerce' );
						}
						break;
					case 'dismiss':
						if ( (bool) $v ) {
							update_user_meta( get_current_user_id(), 'tgmpa_dismissed_notice_bpcast', 1 );
						} else {
							delete_user_meta( get_current_user_id(), 'tgmpa_dismissed_notice_bpcast' );
						}
						break;
					default:
						foreach ( $trans_lang as $pslug => $v ) {
							$lang_slug = $v['lang_slug'];
							$do_copy   = false;
							$po_from   = $bpb_lang_dir . $lang_slug . '-ja.po';
							$mo_from   = $bpb_lang_dir . $lang_slug . '-ja.mo';

							switch ( $key ) {
								case $pslug . '_trans_plugin':
									$plugin_lang_path = WP_CONTENT_DIR . '/plugins/' . $v['plg_slug'] . '/' . $v['lang_dir'] . '/';

									$do_copy = true;
									$po_to   = $plugin_lang_path . $lang_slug . '-ja.po';
									$mo_to   = $plugin_lang_path . $lang_slug . '-ja.mo';

									break;
								case $pslug . '_trans_system':
									$do_copy = true;
									$po_to   = $wpcore_lang_dir . $lang_slug . '-ja.po';
									$mo_to   = $wpcore_lang_dir . $lang_slug . '-ja.mo';

									break;
								case $pslug . '_trans_loco':
									$do_copy = true;
									$po_to   = $loco_lang_dir . $lang_slug . '-ja.po';
									$mo_to   = $loco_lang_dir . $lang_slug . '-ja.mo';

									break;
							}

							if ( $do_copy ) {
								// ! ここを作成する（ファイルの存在をチェック、to dirチェック、コピー成功チェック）
								$flag = copy( $po_from, $po_to );
								if ( $flag ) {
									$msg_success[] = basename( $po_from ) . 'を' . dirname( $po_to ) . 'にコピーしました。';
								} else {
									$msg_error[] = basename( $po_from ) . 'を' . dirname( $po_to ) . 'にコピーできませんでした。';
								}

								$flag = copy( $mo_from, $mo_to );
								if ( $flag ) {
									$msg_success[] = basename( $mo_from ) . 'を' . dirname( $mo_to ) . 'にコピーしました。';
								} else {
									$msg_error[] = basename( $mo_from ) . 'を' . dirname( $mo_to ) . 'にコピーできませんでした。';
								}
							}
						}
				}
			}

			if ( count( $msg_success ) ) {
				echo '<div class="notice notice-success is-dismissible"><p>';
				foreach ( $msg_success as $l ) {
					echo $l . '<br>';
				}
				echo '</p></div>';
			}

			if ( count( $msg_error ) ) {
				echo '<div class="notice notice-error is-dismissible"><p>';
				foreach ( $msg_error as $l ) {
					echo $l . '<br>';
				}
				echo '</p></div>';
			}
		}
		?>

		<div class="wrap">
			<h2>bp-blocks</h2>
			<p>bp-blocks関連の設定を行えます。実行したい処理を選んで、実行ボタンを押してください。</p>

			<form method="post" action="<?php admin_url( 'options-general.php?page=bp-blocks' ); ?>">
			<table class="form-table">
				<tbody>
				<tr>
					<th scope="row">
						<label for="my-text-field">WooCommerceを利用する</label>
					</th>
					<td>
						<?php
						if ( get_option( 'bp_block_use_woocommerce', false ) ) {
							$true_checked = 'checked';
							$false_checked = '';
						} else {
							$true_checked = '';
							$false_checked = 'checked';
						}
						?>
						<label><input type="radio" name="bpb[use_woocommerce]" value="1" <?php echo $true_checked; ?> /> はい、使います</label><br>
						<label><input type="radio" name="bpb[use_woocommerce]" value="0" <?php echo $false_checked; ?> /> いいえ、使いません</label><br>
						<br>
						<span class="description">WooCommerceを使う設定を行うと、推奨プラグインを簡単にインストールできます。</span>
					</td>
				</tr>
				<?php foreach ( $trans_lang as $pslug => $v ) : ?>
				<tr>
					<th scope="row">
						<label for="my-text-field"><?php echo $v['name']; ?>の翻訳ファイルを更新</label>
					</th>
					<td>
						<label><input type="checkbox" name="bpb[<?php echo $pslug; ?>_trans_plugin]" value="true" /> プラグインの言語ファイルを更新する</label><br>
						<label><input type="checkbox" name="bpb[<?php echo $pslug; ?>_trans_system]" value="true" /> システムの言語ファイルを更新する</label><br>
						<label><input type="checkbox" name="bpb[<?php echo $pslug; ?>_trans_loco]" value="true" /> Loco翻訳プラグインの言語ファイルを更新する</label><br>
						<br>
						<span class="description">翻訳ファイルを上書き保存します。必要な設定を行った上で、実行してください（特にLoco Translateプラグイン）</span>
					</td>
				</tr>
				<?php endforeach; ?>
				<tr>
				<th scope="row">
						<label for="my-text-field">システム通知の停止</label>
					</th>
					<td>
						<?php
						if ( get_user_meta( get_current_user_id(), 'tgmpa_dismissed_notice_bpcast', true ) ) {
							$true_checked = 'checked';
							$false_checked = '';
						} else {
							$true_checked = '';
							$false_checked = 'checked';
						}
						?>
						<label><input type="radio" name="bpb[dismiss]" value="1" <?php echo $true_checked; ?> /> 停止します</label><br>
						<label><input type="radio" name="bpb[dismiss]" value="0" <?php echo $false_checked; ?> /> 有効にします</label><br>
						<br>
						<span class="description">プラグインアップデートの通知が出るようにするには、「通知を有効」にしてください</span>
					</td>
				</tr>
				</tbody>
			</table>
			<?php wp_nonce_field( 'bp-blocks' ); ?>
			<input type="hidden" name="cmd" value="bp-blocks-settings" />
			<?php submit_button( '実行' ); ?>
		</form>
		</div>
	<?php }

	public function bp_blocks_page_init() {

	}

	public function bp_blocks_section_info() {
		
	}
}
if ( is_admin() )
	$bp_blocks = new BpBlocks();

/* 
 * Retrieve this value with:
 * $bp_blocks_options = get_option( 'bp_blocks_option_name' ); // Array of All Options
 * $wp_fly_cart__0 = $bp_blocks_options['wp_fly_cart__0']; // WP Fly Cart 日本語ファイルをコピーする
 */
